version: '3.9'

services:
  db:
    image: postgres:latest
    hostname: '127.0.0.1'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # app:
  #     build:
  #       context: .
  #     environment:
  #       PG_DSN: 'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@localhost:5432/{POSTGRES_DB}'
  #     ports:
  #       - '8000:8000'
  #     depends_on:
  #       - db
  #     volumes:
  #       - ./app:/app