version: '3.9'

services:
  db:
    image: postgres:latest
    hostname: '127.0.0.1'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}