@baseUrl = http://0.0.0.0:8080
#@baseUrl = http://127.0.0.1:8080

###

# создать пользователя
POST {{baseUrl}}/user
Content-Type: application/json

{

    "name": "Tony",
    "email": "stark@yandex.ru",
    "password": "user1 password"
    
}


###

# получить пользователя
GET {{baseUrl}}/user/1
Content-Type: application/json


### 

# создать объявление
POST {{baseUrl}}/advert
Content-Type: application/json

{
    "title": "Selling an aquarium fish",
    "description": "Guppi fish, really cute",
    "time_of_creation": "time_of_creation",
    "owner_id": 1
}

### 

# получить объявление
GET {{baseUrl}}/advert/9
Content-Type: application/json

### 

# удалить объявление
DELETE {{baseUrl}}/advert/9
Content-Type: application/json